export const categories = [
    { key: 'purchases', name: 'Compras', icon: 'shopping-bag', color: '#7C3AED' },
    { key: 'food', name: 'Alimentação', icon: 'coffee', color: '#FF872C' },
    { key: 'salary', name: 'Salário', icon: 'dollar-sign', color: '#12A454' },
    { key: 'other-income', name: 'Outras receitas', icon: 'plus-circle', color: '#10B981' },
    { key: 'housing', name: 'Moradia', icon: 'home', color: '#F59E0B' },
    { key: 'car', name: 'Transporte', icon: 'truck', color: '#E83F5B' },
    { key: 'leisure', name: 'Lazer', icon: 'heart', color: '#8B5CF6' },
    { key: 'studies', name: 'Educação', icon: 'book', color: '#EF4444' },
    { key: 'health', name: 'Saúde', icon: 'activity', color: '#3B82F6' },
    { key: 'bills', name: 'Contas e serviços', icon: 'file-text', color: '#64748B' },
    { key: 'taxes', name: 'Impostos e taxas', icon: 'percent', color: '#DC2626' },
    { key: 'subscriptions', name: 'Assinaturas', icon: 'repeat', color: '#0EA5E9' },
    { key: 'pets', name: 'Pets', icon: 'smile', color: '#A855F7' },
    { key: 'gifts', name: 'Presentes e doações', icon: 'gift', color: '#EC4899' },
    { key: 'investments', name: 'Investimentos', icon: 'trending-up', color: '#059669' },
    { key: 'transfers', name: 'Transferências', icon: 'arrow-right', color: '#475569' },
    { key: 'other', name: 'Outros', icon: 'more-horizontal', color: '#78716C' },
];
